#define Z_FEATURE_MULTI_THREAD 1
#define Z_FEATURE_LINK_TCP 0
#define Z_FEATURE_LINK_UDP_UNICAST 1 
#define Z_FEATURE_LINK_UDP_MULTICAST 0
#define configSUPPORT_STATIC_ALLOCATION 1
#define Z_MULTI_THREAD 0